meta_product_name: "Jicama"
meta_title: "Jicama - Your data privacy manager"
meta_description: "Own your data, own your future. Regain data control and see your digital footprint"
meta_image: "cover.png"
twitter_account: "@Lewagonparis"
